# Generated by Django 3.2 on 2023-10-20 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_board_like_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='view_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
